#***************************************************************************
#*                                                                         *
#*   Copyright (c) 2015 microelly <microelly2@freecadbuch.de>              *  
#*                                                                         *
#*   This program is free software; you can redistribute it and/or modify  *
#*   it under the terms of the GNU Lesser General Public License (LGPL)    *
#*   as published by the Free Software Foundation; either version 2 of     *
#*   the License, or (at your option) any later version.                   *
#*   for detail see the LICENCE text file.                                 *
#*                                                                         *
#*   This program is distributed in the hope that it will be useful,       *
#*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
#*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
#*   GNU Library General Public License for more details.                  *
#*                                                                         *
#*   You should have received a copy of the GNU Library General Public     *
#*   License along with this program; if not, write to the Free Software   *
#*   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *
#*   USA                                                                   *
#*                                                                         *
#***************************************************************************

#
# yaml configration file for the plugin management
# see yaml.org
#



plugins:

# 04.05.2015 pcb, cura engine
  pcb:
    status: noignore
    source: http://sourceforge.net/projects/eaglepcb2freecad/files/latest/download?source=files
    #source: http://sourceforge.net/projects/eaglepcb2freecad/files/3.5/PCB.7z/download
    sourcedir: .
    destdir: UserAppData/Mod/PCB
    menu: PCB Workbench
    exec: FreeCADGui.activateWorkbench("PCB")
    icon: UserAppData/Mod/PCB/data/board.svg

    method: 7z
    
    

  curaengin:
    status: noignore
    source: https://github.com/cblt2l/FreeCAD-CuraEngine-Plugin/archive/master.zip
    destdir: UserAppData/Mod/curaengine
    backup: UserAppData/Mod/curaengine
    sourcedir: FreeCAD-CuraEngine-Plugin-master
    menu: Cura Engine Workbench
    # exec: FreeCADGui.activateWorkbench("TDPrinting")



  assembly2:
    name: assembly2
    status: noignore
    description: Assembly Workbench in python
    author: hamish2914
    
    # mandatory attributes
    source: https://github.com/hamish2014/FreeCAD_assembly2/archive/master.zip
    method: zip
    sourcedir: FreeCAD_assembly2-master
    
    destdir: UserAppData/Mod/assembly2
    backup: UserAppData/Mod/assembly2
    menu: Assembly2 Workbench
    exec: FreeCADGui.activateWorkbench("Assembly2Workbench")
    icon: AppHomePath/Mod/plugins/icons/assembly2.png


  drawing dimensioning : 
    status: noignore
    name: drawing Dimsioning
    description : Drawing Dim ...
    
    # display information about this package
    info: https://github.com/hamish2014/FreeCAD_drawing_dimensioning/blob/master/README.md
    
    # display commit log
    history: https://github.com/hamish2014/FreeCAD_drawing_dimensioning/commits/master/
    author: hamish2914
    source: https://github.com/hamish2014/FreeCAD_drawing_dimensioning/archive/master.zip
    sourcedir: FreeCAD_drawing_dimensioning-master
    timestamp: https://github.com/hamish2014/FreeCAD_assembly2/master/release

    # local installation
    destdir: UserAppData/Mod/drawing_dimensioning

    # installation for all users
    #destdir: AppHomePath/Mod/plugins/drawing_dimensioning
    menu: Drawing Dimensioning Workbench
    exec: FreeCADGui.activateWorkbench("DrawingDimensioningWorkbench")
    icon: AppHomePath/Mod/plugins/icons/drawing_dim.png

  sipoc : 
    name: sipoc
    status: ignore
    description : Single Point Configuration
    author: microelly2
    source: https://github.com/microelly2/freecad-sipoc/archive/master.zip
    sourcedir: freecad-sipoc-master
    timestamp: https://raw.githubusercontent.com/microelly2/freecad-sipoc/master/release
    destdir: AppHomePath/Mod/plugins/plugin3
    
    # only one single menu entry
    #menu: sipoc - command3
    #exec: import plugins;plugins.plugin1.info2()


  workfeature:
     name: workfeature 
     status: noignore
     source: https://github.com/Rentlau/WorkFeature/archive/master.zip
     timestamp: 00
     sourcedir: WorkFeature-master
     destdir: AppHomePath/Mod/plugins/WorkFeature
     menu: Workfeature Macro
     exec: fn="AppHomePath/Mod/plugins/WorkFeature/start_WF.FCMacro";exec open(fn).read()
     icon: AppHomePath/Mod/plugins/icons/WF_wf.png
  
  
  assembly animation dropbox:
     comment: demo for dropbox download
     name: ExplodedAssemblyAnimation
     status: ignore
     source:  https://www.dropbox.com/s/qxvtavsp4g539jq/ExplodedAssemblyAnimation.zip?dl=1
     author: JMG
     timestamp: 
     sourcedir: ExplodedAssemblyAnimation
     destdir: UserAppData/Mod/ExplodedAssemblyAnimation
     backup: UserAppData/Mod/ExplodedAssemblyAnimation

  assembly animation: &yy
     name: ExplodedAssemblyAnimation
     status: noignore
     source:  https://github.com/JMG1/FreeCAD_ExplodedAssemblyAnimationWorkbench/archive/master.zip
     author: JMG
     timestamp: 
     sourcedir: FreeCAD_ExplodedAssemblyAnimationWorkbench-master
     destdir: UserAppData/Mod/ExplodedAssemblyAnimation
     menu: Assembly Animation Workbench
     exec: FreeCADGui.activateWorkbench("ExplodedAnimation")
     icon: AppHomePath/Mod/plugins/icons/icon_createroute.png




  bolts:
     name: bolts 
     status: noignore
     source: http://www.bolts-library.org/de/downloads/freecad/BOLTS_FreeCAD_0.3_lgpl2.1+.zip
     timestamp: 00
     sourcedir: BOLTS
     destdir: AppHomePath/Mod/BOLTS
     menu: Bolts Library
     exec: import BOLTS;BOLTS.show_widget()
     icon: AppHomePath/Mod/plugins/icons/bolts.png
     requires: pyside-tools 
   
#------------------------



  symbollib:
     name: symbols
     status: noignore
     source: https://github.com/FreeCAD/FreeCAD-symbols/archive/master.zip
     author: yorik
     description: symbols for drawing page
     timestamp: 00
     sourcedir: FreeCAD-symbols-master
     destdir:  AppHomePath/Mod/plugins/FreeCAD-symbols
     backup:  AppHomePath/Mod/plugins/FreeCAD-symbols
     menu: Drawing Symbols Library
     exec: fn="AppHomePath/Mod/plugins/FreeCAD-symbols/SymbolsLibrary.FCMacro";exec open(fn).read()
     icon: AppHomePath/Mod/plugins/icons/first_angle.png

  partlib:
     name: partlib
     status: noignore
     source: https://github.com/yorikvanhavre/FreeCAD-library/archive/master.zip
     author: yorik
     timestamp: 00
     sourcedir: FreeCAD-library-master
     #destdir:  AppHomePath/Mod/plugins/FreeCAD-symbols
     destdir: /tmp/test
     menu: Parts Library
     exec: fn="AppHomePath/Mod/plugins/FreeCAD-library/PartsLibrary.FCMacro";exec open(fn).read()
     icon: AppHomePath/Mod/plugins/icons/master.png

#------------------------

  circular text:
    status: noignore
    source: http://forum.freecadweb.org/download/file.php?id=11170
    sourcedir: .
    destdir: UserAppData/Macros/circular_text.py
    format: flatfile
    menu: Circular Text Macro
    exec: fn="AppHomePath/Mod/plugins/FreeCAD-library/PartsLibrary.FCMacro";exec open(fn).read()
    icon: AppHomePath/Mod/plugins/icons/circulartext.png
    
    
    
  screw maker:
    status: noignore
    source: http://forum.freecadweb.org/download/file.php?id=5449
    author: ulrich brammer
    sourcedir: .
    destdir: UserAppData/Macros/screw_maker.py
    format: zipfile
    menu: Screw Maker Macro
    exec: fn="UserAppData/Macros/screw_maker1_7.py";exec open(fn).read()

#------------------------
#
#  FreeCAD macrolib
#
#--------------------------

  FreeCAD-makros:
    status: noignore
    source:  https://github.com/FreeCAD/FreeCAD-macros/archive/master.zip
    sourcedir: FreeCAD-macros-master
    destdir: /tmp/FreeCAD-macros
    format: zip

#----------------------------
  menutest2:
    name: sipoc
    status: noignore
    description : Single Point Configuration
    author: microelly2
    source: https://github.com/microelly2/freecad-sipoc/archive/master.zip
    sourcedir: freecad-sipoc-master
    timestamp: https://raw.githubusercontent.com/microelly2/freecad-sipoc/master/release
    destdir: AppHomePath/Mod/plugins/plugin3
    menu: Single Point Configuration Macro
    
     # install this module with 3 menu items
    menuitems:
        menu test - command1:
           exec: import plugins;plugins.plugin1.info2()
        menu test - cmd2:
           exec: import plugins;plugins.plugin1.p1.info1()

        # its possible to add useful commands too
        menu tes - fun:
           exec:  FreeCAD.ActiveDocument.addObject("Part::Box","Box")
  animation:
    status: noignore
    menu: Animation Workbench
    icon: AppHomePath/Mod/Animation/icons/animation.png
  
  
  loadtest:
    status: noignore
    name: loader test
    source: https://github.com/microelly2/freecad-sipoc/archive/master.zip
    sourcedir: freecad-sipoc-master

    #destdir: /tmp/destdir
    destdir: UserAppData/Mod/testdir
    #destdir: UserHomePath/testdir
    #destdir: AppHomePath/Mod/testdir


  defaulttest:
    status: ignore
    destdir:
      Linux: UserAppData/Mod/testdir
      Windows: c:/haha
    backup: UserHomePath/tmp/bak_
    icon: AppHomePath/Mod/plugins/icons/master.png

# defaults:
# if you don not specify parameters for your package
# the following defaults will be used

defaults: &defaults
    name: defaultName
    description: no description 
    author: noname
    status: ignore
    source: https://github.com/microelly2/plugin_defaults/archive/master.zip
    sourcedir: plugin_defaults-master
    destdir: /tmp/destdir
    timestime: https://github.com/microelly2/plugin_defaults/timestamp
    menu: defaults
    exec: import FreeCAD;FreeCAD.Console.PrintWarning('*****default Method FreeCAD-Dir=AppHomePath/! HOME-Dir=UserHomePath/!  UserData-Dir=UserAppData/!\n')
    backup: UserHomePath/tmp/bak_
    format: zipdir 
    method: zip
    icon: AppHomePath/Mod/plugins/icons/master.png
 
 
# base:
# configurations of the plugin itself 
 
base:
  # verzeichnis temp zum zwischenspeichern und auspacken
  zipex: UserHomePath/tmp/yyya
  tmprelease: UserHomePath/tmp/release











# database of buttons
data:
  Animat: &Anim
    exec: FreeCADGui.activateWorkbench("AnimationWorkbench")
  Arch: &Arch
    exec: FreeCADGui.activateWorkbench("ArchWorkbench")
  Assembyl2: &Ass2
    exec: FreeCADGui.activateWorkbench("Assembly2Workbench")
  Draft: &Draft
    exec: FreeCADGui.activateWorkbench("DraftWorkbench")
  Drawing: &Dang
    exec: FreeCADGui.activateWorkbench("DrawingWorkbench")
  DrawingDim: &Ddim
    exec: FreeCADGui.activateWorkbench("DrawingDimensioningWorkbench")
  Exploded: &Exan
    exec: FreeCADGui.activateWorkbench("ExplodedAnimation")
  Image: &Imag
    exec: FreeCADGui.activateWorkbench("ImageWorkbench")
  Inspection: &Insp
    exec: FreeCADGui.activateWorkbench("InspectionWorkbench")
  Mesh: &Mesh
    exec: FreeCADGui.activateWorkbench("MeshWorkbench")
  OpenSCAD: &Scad
    exec: FreeCADGui.activateWorkbench("OpenSCADWorkbench")
  Plot: &Plot
    exec: FreeCADGui.activateWorkbench("PlotWorkbench")
  Points: &Poin
    exec: FreeCADGui.activateWorkbench("PointsWorkbench")
  PCB: &Pcb
    exec: FreeCADGui.activateWorkbench("PCB")
  Raytraicing: &Rayt
    exec: FreeCADGui.activateWorkbench("RaytracingWorkbench")
  Reference: &Refe
    exec: FreeCADGui.activateWorkbench("ReferenceWorkbench")
  Reverse: &Rein
    exec: FreeCADGui.activateWorkbench("ReverseEngineeringWorkbench")
  Robot: &Robo
    exec: FreeCADGui.activateWorkbench("RobotWorkbench")
  Ship: &Ship
    exec: FreeCADGui.activateWorkbench("ShipWorkbench")
  Sketcher: &Sket
    exec: FreeCADGui.activateWorkbench("SketcherWorkbench")
  Spreedsheet: &Calc
    exec: FreeCADGui.activateWorkbench("SpreadsheetWorkbench")
  Start: &Start
    exec: FreeCADGui.activateWorkbench("StartWorkbench")
  Test: &Test
    exec: FreeCADGui.activateWorkbench("TestWorkbench")
  Web: &Web
    exec: FreeCADGui.activateWorkbench("WebWorkbench")
  PartDesignWorkbench: &PartDesign
    exec: FreeCADGui.activateWorkbench("PartDesignWorkbench")
    icon:  AppHomePath/Mod/plugins/icons/part.png
  PartWorkbench: &Part
    exec: FreeCADGui.activateWorkbench("PartWorkbench")
    icon:  AppHomePath/Mod/plugins/icons/part.png
  FEMWorkbench: &FEM
    exec: FreeCADGui.activateWorkbench("FemWorkbench")
    icon:  AppHomePath/Mod/plugins/icons/fem.png
#  ShipWorkbench: &Ship
#    exec: FreeCADGui.activateWorkbench("ShipWorkbench")
#    icon:  AppHomePath/Mod/plugins/icons/ship.png
#  RobotWorkbench: &Robot
#    exec: FreeCADGui.activateWorkbench("RobotWorkbench")
#    icon:  AppHomePath/Mod/plugins/icons/robot.png

# tabs of the manager window
tabs:
  My Favorites:
    PartDesign: *PartDesign
    Part: *Part
    # deactivate entry ...
    #Robot:*Robot
    FEM: *FEM

  Other Workbenches: 
    # reuse entries by links 
    1 Part: *Part
    2 Ship: *Ship
    3 Robot: *Robo
    # create individual entries outside the database
    4 Dummy: 
      exec: import FreeCAD;FreeCAD.Console.PrintWarning("Nothing to do!")
      icon:  AppHomePath/Mod/plugins/icons/master.png
    6 Greeting: 
      exec: FreeCAD.Console.PrintWarning("Hello World!")
      icon:  AppHomePath/Mod/plugins/icons/sun.png
    5 Create Box:
      exec:  FreeCAD.ActiveDocument.addObject("Part::Box","Box")
      icon:  AppHomePath/Mod/plugins/icons/part.png
  WB2:
    Animat: *Anim
    Arch: *Arch
    Assembyl2: *Ass2
    Draft: *Draft
    Drawing: *Dang
    DrawingDim: *Ddim
    Exploded: *Exan
    Image: *Imag
    Inspection: *Insp
    Mesh: *Mesh
  WB3:
    OpenSCAD: *Scad
    Plot: *Plot
    Points: *Poin
    PCB: *Pcb
    Raytraicing: *Rayt
    Reference: *Refe
    Reverse: *Rein
    Robot: *Robo
    Ship: *Ship
    Sketcher: *Sket
    Spreedsheet: *Calc
    Start: *Start
    Test: *Test
    Web: *Web


