#***************************************************************************
#*                                                                         *
#*   Copyright (c) 2015 microelly <microelly2@freecadbuch.de>              *  
#*                                                                         *
#*   This program is free software; you can redistribute it and/or modify  *
#*   it under the terms of the GNU Lesser General Public License (LGPL)    *
#*   as published by the Free Software Foundation; either version 2 of     *
#*   the License, or (at your option) any later version.                   *
#*   for detail see the LICENCE text file.                                 *
#*                                                                         *
#*   This program is distributed in the hope that it will be useful,       *
#*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
#*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
#*   GNU Library General Public License for more details.                  *
#*                                                                         *
#*   You should have received a copy of the GNU Library General Public     *
#*   License along with this program; if not, write to the Free Software   *
#*   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *
#*   USA                                                                   *
#*                                                                         *
#***************************************************************************

#
# yaml configration file for the plugin management
# see yaml.org
#


plugins:
  assembly2:
    name: assembly2
    status: noignore
    description: Assembly Workbench in python
    author: hamish2914
    
    # mandatory attributes
    source: https://github.com/hamish2014/FreeCAD_assembly2/archive/master.zip
    method: zip
    sourcedir: FreeCAD_assembly2-master
    
    destdir: /home/microelly2/.FreeCAD/Mod/assembly2
    backup: /home/microelly2/.FreeCAD/Mod/assembly2
    menu: Assembyl2 Workbench
    exec: FreeCADGui.activateWorkbench("Assembly2Workbench")
    icon: /usr/lib/freecad/Mod/plugins/icons/assembly2.png


  drawing dimensioning : 
    status: noignore
    name: drawing Dimsioning
    description : Drawing Dim ...
    
    # display information about this package
    info: https://github.com/hamish2014/FreeCAD_drawing_dimensioning/blob/master/README.md
    
    # display commit log
    history: https://github.com/hamish2014/FreeCAD_drawing_dimensioning/commits/master/
    author: hamish2914
    source: https://github.com/hamish2014/FreeCAD_drawing_dimensioning/archive/master.zip
    sourcedir: FreeCAD_drawing_dimensioning-master
    timestamp: https://github.com/hamish2014/FreeCAD_assembly2/master/release

    # local installation
    destdir: /home/microelly2/.FreeCAD/Mod/drawing_dimensioning

    # installation for all users
    #destdir: /usr/lib/freecad/Mod/plugins/drawing_dimensioning
    menu: Drawing Dimensioning Workbench
    exec: FreeCADGui.activateWorkbench("DrawingDimensioningWorkbench")
    icon: /usr/lib/freecad/Mod/plugins/icons/drawing_dim.png

  sipoc : 
    name: sipoc
    status: ignore
    description : Single Point Configuration
    author: microelly2
    source: https://github.com/microelly2/freecad-sipoc/archive/master.zip
    sourcedir: freecad-sipoc-master
    timestamp: https://raw.githubusercontent.com/microelly2/freecad-sipoc/master/release
    destdir: /usr/lib/freecad/Mod/plugins/plugin3
    
    # only one single menu entry
    #menu: sipoc - command3
    #exec: import plugins;plugins.plugin1.info2()


  workfeature:
     name: workfeature 
     status: noignore
     source: https://github.com/Rentlau/WorkFeature/archive/master.zip
     timestamp: 00
     sourcedir: WorkFeature-master
     destdir: /usr/lib/freecad/Mod/plugins/WorkFeature
     menu: Workfeature Macro
     exec: fn="/usr/lib/freecad/Mod/plugins/WorkFeature/start_WF.FCMacro";exec open(fn).read()
     icon: /usr/lib/freecad/Mod/plugins/icons/WF_wf.png
  
  
  assembly animation dropbox:
     comment: demo for dropbox download
     name: ExplodedAssemblyAnimation
     status: ignore
     source:  https://www.dropbox.com/s/qxvtavsp4g539jq/ExplodedAssemblyAnimation.zip?dl=1
     author: JMG
     timestamp: 
     sourcedir: ExplodedAssemblyAnimation
     destdir: /home/microelly2/.FreeCAD/Mod/ExplodedAssemblyAnimation
     backup: /home/microelly2/.FreeCAD/Mod/ExplodedAssemblyAnimation

  assembly animation:
     name: ExplodedAssemblyAnimation
     status: noignore
     source:  https://github.com/JMG1/FreeCAD_ExplodedAssemblyAnimationWorkbench/archive/master.zip
     author: JMG
     timestamp: 
     sourcedir: FreeCAD_ExplodedAssemblyAnimationWorkbench-master
     destdir: /home/microelly2/.FreeCAD/Mod/ExplodedAssemblyAnimation
     menu: Assembly Animation Workbench
     exec: FreeCADGui.activateWorkbench("ExplodedAnimation")
     icon: /usr/lib/freecad/Mod/plugins/icons/icon_createroute.png




  bolts:
     name: bolts 
     status: noignore
     source: http://www.bolts-library.org/de/downloads/freecad/BOLTS_FreeCAD_0.3_lgpl2.1+.zip
     timestamp: 00
     sourcedir: BOLTS
     destdir: /usr/lib/freecad/Mod/BOLTS
     menu: Bolts Library
     exec: import BOLTS;BOLTS.show_widget()
     icon: /usr/lib/freecad/Mod/plugins/icons/bolts.png
     requires: pyside-tools 
   
#------------------------



  symbollib:
     name: symbols
     status: noignore
     source: https://github.com/FreeCAD/FreeCAD-symbols/archive/master.zip
     author: yorik
     description: symbols for drawing page
     timestamp: 00
     sourcedir: FreeCAD-symbols-master
     destdir:  /usr/lib/freecad/Mod/plugins/FreeCAD-symbols
     backup:  /usr/lib/freecad/Mod/plugins/FreeCAD-symbols
     menu: Drawing Symbols Library
     exec: fn="/usr/lib/freecad/Mod/plugins/FreeCAD-symbols/SymbolsLibrary.FCMacro";exec open(fn).read()
     icon: /usr/lib/freecad/Mod/plugins/icons/first_angle.png

  partlib:
     name: partlib
     status: noignore
     source: https://github.com/yorikvanhavre/FreeCAD-library/archive/master.zip
     author: yorik
     timestamp: 00
     sourcedir: FreeCAD-library-master
     #destdir:  /usr/lib/freecad/Mod/plugins/FreeCAD-symbols
     destdir: /tmp/test
     menu: Parts Library
     exec: fn="/usr/lib/freecad/Mod/plugins/FreeCAD-library/PartsLibrary.FCMacro";exec open(fn).read()
     icon: /usr/lib/freecad/Mod/plugins/icons/master.png

#------------------------

  circular text:
    status: noignore
    source: http://forum.freecadweb.org/download/file.php?id=11170
    sourcedir: .
    destdir: /home/microelly2/.FreeCAD/Macros/circular_text.py
    format: flatfile
    menu: Circular Text Macro
    exec: fn="/usr/lib/freecad/Mod/plugins/FreeCAD-library/PartsLibrary.FCMacro";exec open(fn).read()
    icon: /usr/lib/freecad/Mod/plugins/icons/circulartext.png
    
    
    
  screw maker:
    status: noignore
    source: http://forum.freecadweb.org/download/file.php?id=5449
    sourcedir: .
    destdir: /home/microelly2/.FreeCAD/Macros/screw_maker.py
    format: zipfile

#------------------------
#
#  FreeCAD macrolib
#
#--------------------------

  FreeCAD-makros:
    status: noignore
    source:  https://github.com/FreeCAD/FreeCAD-macros/archive/master.zip
    sourcedir: FreeCAD-macros-master
    destdir: /tmp/FreeCAD-macros
    format: zip

#----------------------------
  menutest2:
    name: sipoc
    status: ignore
    description : Single Point Configuration
    author: microelly2
    source: https://github.com/microelly2/freecad-sipoc/archive/master.zip
    sourcedir: freecad-sipoc-master
    timestamp: https://raw.githubusercontent.com/microelly2/freecad-sipoc/master/release
    destdir: /usr/lib/freecad/Mod/plugins/plugin3
    
     # install this module with 3 menu items
    menuitems:
        menu test - command1:
           exec: import plugins;plugins.plugin1.info2()
        menu test - cmd2:
           exec: import plugins;plugins.plugin1.p1.info1()

        # its possible to add useful commands too
        menu tes - fun:
           exec:  FreeCAD.ActiveDocument.addObject("Part::Box","Box")

  loadtest:
    status: ignore
    name: loader test
    source: https://github.com/microelly2/freecad-sipoc/archive/master.zip
    sourcedir: freecad-sipoc-master
    destdir: /tmp/destdir

  defaulttest:
    status: ignore


# defaults:
# if you don not specify parameters for your package
# the following defaults will be used

defaults:
    name: defaultName
    description: no description 
    author: noname
    status: ignore
    source: https://github.com/microelly2/plugin_defaults/archive/master.zip
    sourcedir: plugin_defaults-master
    destdir: /tmp/destdir
    timestime: https://github.com/microelly2/plugin_defaults/timestamp
    menu: defaults
    exec: import FreeCAD;FreeCAD.Console.PrintWarning('******************default Method\n')
    backup: /tmp/bak_
    format: zipdir 
 
 
# base:
# configurations of the plugin itself 
 
base:
  # verzeichnis temp zum zwischenspeichern und auspacken
  zipex: /tmp/yyya
  tmprelease: /tmp/release


